import './global.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout } from 'antd';
import Header from '../component/header';
import Footer from '../component/footer';
export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <Layout>
            <Header></Header>
            {children}
            <Footer></Footer>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
